"""create initial tables

Revision ID: f947491cb50e
Revises: 
Create Date: 2026-09-24 11:58:54.165248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f947491cb50e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'SELLER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('normal_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('group_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('minimum_buyers', sa.Integer(), nullable=False),
    sa.Column('maximum_quantity', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUCCESSFUL', 'FAILED', name='dealstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('group_price < normal_price', name='check_group_price_less_than_normal'),
    sa.CheckConstraint('group_price > 0', name='check_group_price_positive'),
    sa.CheckConstraint('maximum_quantity >= minimum_buyers', name='check_maximum_quantity'),
    sa.CheckConstraint('minimum_buyers > 0', name='check_minimum_buyers_positive'),
    sa.CheckConstraint('normal_price > 0', name='check_normal_price_positive'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_deadline'), 'deals', ['deadline'], unique=False)
    op.create_index(op.f('ix_deals_id'), 'deals', ['id'], unique=False)
    op.create_index(op.f('ix_deals_seller_id'), 'deals', ['seller_id'], unique=False)
    op.create_table('participations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('JOINED', 'CANCELLED', name='participationstatus'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id', 'customer_id', name='uq_deal_customer')
    )
    op.create_index(op.f('ix_participations_customer_id'), 'participations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_participations_deal_id'), 'participations', ['deal_id'], unique=False)
    op.create_index(op.f('ix_participations_id'), 'participations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participations_id'), table_name='participations')
    op.drop_index(op.f('ix_participations_deal_id'), table_name='participations')
    op.drop_index(op.f('ix_participations_customer_id'), table_name='participations')
    op.drop_table('participations')
    op.drop_index(op.f('ix_deals_seller_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_deadline'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
